### ISSUE TITLE
R 3.5.0?

### ISSUE THREAD

**Issue by muschellij2** [paulhibbing/AGread#23]
Why do we have this? https://github.com/paulhibbing/AGread/blob/master/R/zzz.R#L6

**Comment by paulhibbing** [comment]
I am horrible about upgrading, so I run 3.5.0 on my primary machine. It's a good idea for others to be alerted to that when they attach `AGread`, in case they know of relevant behaviors that have changed between 3.5.0 and whatever version they're running.

I get similar messages for other packages when I attach them, e.g. `magrittr`, `dplyr`, and `lubridate`. See also ["When you **do** need side effects"](http://r-pkgs.had.co.nz/r.html#r-differences). (Sorry you have to scroll down a bit...)
